<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE root [
<!ELEMENT root (employees+,companies+)>
<!ELEMENT employees (employee+)>
<!ELEMENT companies (company+)>
<!ELEMENT employee (#PCDATA)>
<!ATTLIST employee id CDATA #REQUIRED>
<!ELEMENT company (#PCDATA)>
<!ATTLIST company id CDATA #REQUIRED>
]>

<root>
  <employees>
    <employee id="1">Johnny Dapp</employee>
    <employee id="2">Al Pacino</employee>
    <employee id="3">Robert De Niro</employee>
    <employee id="4">Kevin Spacey</employee>
    <employee id="5">Denzel Washington</employee>
  </employees>
  <companies>
    <company id="6">Tata Consultancy Services</company>
    <company id="7">Wipro</company>
    <company id="8">Infosys</company>
    <company id="9">Microsoft</company>
    <company id="10">IBM</company>
    <company id="11">Apple</company>
    <company id="12">Oracle</company>
  </companies>
</root>
